### ISSUE TITLE
Enhance Python bindings

### ISSUE THREAD

**Issue by erikcs** [grf-labs/maq#35]
- [x] Horizontal line indicating a plateau in plot(). #58
- [x] Tag new devel release + update py changelog.
- [x] Sync with R functionality. #47
- [x] Cleanups. #47
- [x] A Python changelog. #47
- [x] Use a jupyter notebook for a simple example. #47

Ref: https://github.com/uber/causalml/issues/662
